license="MIT"

modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory
issueTrackerURL="https://github.com/lumien231/Chunk-Animator" #optional

displayURL="https://minecraft.curseforge.com/projects/chunk-animator" #optional

authors="Lumien" #optional
credits="Harley O'Connor for this 1.16 Port"

[[mods]] #mandatory

modId="chunkanimator" #mandatory

version="1.2" #mandatory

displayName="Chunk Animator" #mandatory

description='''
A small client side mod that animates the appeareance of chunks so that they don't just instantly appear
'''

[[dependencies.chunkanimator]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chunkanimator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"